export const categories = [
  {
    prefix: 'ao',
    id: 'airside-operations',
    label: 'Airside Operations',
    description: 'Flight punctuality and schedule adherence',
  },
  {
    prefix: 'tm',
    id: 'turnaround-management',
    label: 'Turnaround Management',
    description: 'Ground milestones and aircraft readiness',
  },
  {
    prefix: 'ro',
    id: 'runway-operations',
    label: 'Runway Operations',
    description: 'Movement, occupancy and available capacity',
  },
  {
    prefix: 'ap',
    id: 'apron-operations',
    label: 'Apron Operations',
    description: 'Stands, taxi routes and surface congestion',
  },
  {
    prefix: 'as',
    id: 'airside-safety',
    label: 'Airside Safety',
    description: 'Events, exposure and response performance',
  },
  {
    prefix: 'gs',
    id: 'ground-support-resources',
    label: 'Ground Support / Resources',
    description: 'Equipment availability and resource allocation',
  },
  {
    prefix: 'wl',
    id: 'weather-lvp',
    label: 'Weather / LVP',
    description: 'Weather readiness and operational disruption',
  },
  {
    prefix: 'oe',
    id: 'operational-efficiency',
    label: 'Operational Efficiency',
    description: 'Capacity, efficiency and recovery',
  },
  {
    prefix: 'ra',
    id: 'reporting-analytics',
    label: 'Reporting & Analytics',
    description: 'Reporting quality and operational assurance',
  },
  {
    prefix: 'to',
    id: 'terminal-operations',
    label: 'Terminal Operations',
    description: 'Baggage, counters and passenger scenarios',
  },
  {
    prefix: 'pf',
    id: 'passenger-flow',
    label: 'Passenger Flow',
    description: 'Passenger capacity, processing and experience',
  },
] as const;
export type CategoryId = (typeof categories)[number]['id'];
export const entries = [
  {
    id: 'ao-otp-all',
    title: 'On-Time Performance (OTP) – All Flights',
    visual: 'Percentage/donut, arrival/departure trend and eligible counts',
    category: 'airside-operations',
  },
  {
    id: 'ao-otp-base',
    title: 'OTP – Base/Hub Carrier Flights',
    visual: 'Base-carrier OTP trend and carrier breakdown',
    category: 'airside-operations',
  },
  {
    id: 'ao-sobt',
    title: 'SOBT Adherence',
    visual: 'Departure adherence %, tolerance bands and flight table',
    category: 'airside-operations',
  },
  {
    id: 'ao-sibt',
    title: 'SIBT Adherence',
    visual: 'Arrival adherence %, tolerance bands and flight table',
    category: 'airside-operations',
  },
  {
    id: 'ao-aobt',
    title: 'AOBT Deviation',
    visual: 'Signed actual off-block minus scheduled off-block distribution',
    category: 'airside-operations',
  },
  {
    id: 'ao-aibt',
    title: 'AIBT Deviation',
    visual: 'Signed actual in-block minus scheduled in-block distribution',
    category: 'airside-operations',
  },
  {
    id: 'ao-base-delay-60',
    title: 'Base Flight Delay >60 min',
    visual: 'Count plus eligible-flight percentage and affected-flight table',
    category: 'airside-operations',
  },
  {
    id: 'ao-departure-delay',
    title: 'Average Departure Delay',
    visual: 'Minutes trend and carrier breakdown',
    category: 'airside-operations',
  },
  {
    id: 'ao-arrival-delay',
    title: 'Average Arrival Delay',
    visual: 'Minutes trend and carrier breakdown',
    category: 'airside-operations',
  },
  {
    id: 'tm-turnaround-time',
    title: 'Aircraft Turnaround Time',
    visual: 'Minutes by aircraft type/carrier with target',
    category: 'turnaround-management',
  },
  {
    id: 'tm-milestones',
    title: 'Turnaround Milestone Adherence',
    visual: 'Milestone adherence bars and per-turn timeline',
    category: 'turnaround-management',
  },
  {
    id: 'tm-turnaround-delay',
    title: 'Aircraft Turnaround Delay',
    visual: 'Actual duration minus planned duration, delayed-turn table',
    category: 'turnaround-management',
  },
  {
    id: 'tm-tobt',
    title: 'TOBT Adherence',
    visual: 'Target off-block adherence and deviation distribution',
    category: 'turnaround-management',
  },
  {
    id: 'tm-tsat',
    title: 'TSAT Adherence',
    visual: 'Actual start-up approval versus target, adherence trend',
    category: 'turnaround-management',
  },
  {
    id: 'tm-ground-time',
    title: 'Ground Time Utilization',
    visual: 'Productive ground-service time versus eligible ground time',
    category: 'turnaround-management',
  },
  {
    id: 'ro-utilization',
    title: 'Runway Utilization',
    visual: 'Occupied-time percentage and interval timeline',
    category: 'runway-operations',
  },
  {
    id: 'ro-occupancy',
    title: 'Runway Occupancy Time',
    visual: 'Occupancy seconds per movement, distribution by runway',
    category: 'runway-operations',
  },
  {
    id: 'ro-incursions',
    title: 'Runway Incursion Events',
    visual: 'Incident count and event timeline/table',
    category: 'runway-operations',
  },
  {
    id: 'ro-configuration',
    title: 'Runway Configuration Utilization',
    visual: 'Time share per runway configuration',
    category: 'runway-operations',
  },
  {
    id: 'ro-capacity',
    title: 'Runway Capacity Utilization',
    visual: 'Movements versus declared capacity in matching intervals',
    category: 'runway-operations',
  },
  {
    id: 'ro-throughput',
    title: 'Arrival/Departure Throughput',
    visual: 'Arrivals and departures per time interval',
    category: 'runway-operations',
  },
  {
    id: 'ap-occupancy',
    title: 'Apron Occupancy Rate',
    visual: 'Occupied eligible stand-minutes versus available stand-minutes',
    category: 'apron-operations',
  },
  {
    id: 'ap-congestion',
    title: 'Apron Congestion Index',
    visual: 'Labeled demo index with component breakdown',
    category: 'apron-operations',
  },
  {
    id: 'ap-stand-utilization',
    title: 'Stand Utilization',
    visual: 'Stand matrix and occupancy timeline',
    category: 'apron-operations',
  },
  {
    id: 'ap-allocation-conflicts',
    title: 'Stand Allocation Conflicts',
    visual: 'Conflicting assignment count and time overlap table',
    category: 'apron-operations',
  },
  {
    id: 'ap-vdgs',
    title: 'VDGS Compliance',
    visual: 'Compliant eligible docking events %, exceptions table',
    category: 'apron-operations',
  },
  {
    id: 'ap-taxi-time',
    title: 'Aircraft Taxi Time',
    visual: 'Taxi-in/out duration by runway and stand',
    category: 'apron-operations',
  },
  {
    id: 'ap-taxi-deviation',
    title: 'Taxi-Time Deviation',
    visual: 'Observed minus reference taxi time distribution',
    category: 'apron-operations',
  },
  {
    id: 'ap-taxiway-congestion',
    title: 'Taxiway Congestion',
    visual: 'Segment occupancy/queue heatmap without requiring a real map',
    category: 'apron-operations',
  },
  {
    id: 'ap-taxi-proximity',
    title: 'Aircraft Taxiing Proximity Events',
    visual: 'Count and taxi-phase event table',
    category: 'apron-operations',
  },
  {
    id: 'as-incursion-rate',
    title: 'Runway Incursion Rate',
    visual: 'Rate with event count, exposure and configured scale',
    category: 'airside-safety',
  },
  {
    id: 'as-aircraft-vehicle',
    title: 'Aircraft–Vehicle Conflict Events',
    visual: 'Classified event count and severity breakdown',
    category: 'airside-safety',
  },
  {
    id: 'as-aircraft-aircraft',
    title: 'Aircraft–Aircraft Proximity Events',
    visual: 'Classified event count, phase and location table',
    category: 'airside-safety',
  },
  {
    id: 'as-aircraft-obstacle',
    title: 'Aircraft–Structure/Obstacle Events',
    visual: 'Classified event count and location table',
    category: 'airside-safety',
  },
  {
    id: 'as-fod',
    title: 'FOD Detection/Response Time',
    visual: 'Separate detection latency and response duration where measurable',
    category: 'airside-safety',
  },
  {
    id: 'as-wildlife',
    title: 'Wildlife Strike/Event Rate',
    visual: 'Separate strike/event counts and rates with exposure',
    category: 'airside-safety',
  },
  {
    id: 'as-follow-me-availability',
    title: 'Follow-Me Vehicle Availability',
    visual: 'Available service minutes versus required service minutes',
    category: 'airside-safety',
  },
  {
    id: 'as-follow-me-response',
    title: 'Follow-Me Response Time',
    visual: 'Request-to-arrival minutes and open-request age',
    category: 'airside-safety',
  },
  {
    id: 'gs-gpu',
    title: 'GPU Utilization',
    visual: 'GPU in-use minutes versus serviceable available minutes',
    category: 'ground-support-resources',
  },
  {
    id: 'gs-apu-gpu',
    title: 'APU Usage vs. GPU Availability',
    visual: 'APU minutes paired with GPU availability for matching turns',
    category: 'ground-support-resources',
  },
  {
    id: 'gs-pbb',
    title: 'PBB Utilization',
    visual: 'Bridge usage percentage and resource timeline',
    category: 'ground-support-resources',
  },
  {
    id: 'gs-pbb-idle',
    title: 'PBB Idle Time',
    visual: 'Idle serviceable minutes by passenger boarding bridge',
    category: 'ground-support-resources',
  },
  {
    id: 'gs-resource-utilization',
    title: 'Airside Resource Utilization',
    visual: 'Utilization by resource type and period',
    category: 'ground-support-resources',
  },
  {
    id: 'gs-allocation-success',
    title: 'Resource Allocation Success Rate',
    visual: 'Fulfilled eligible requests %, failed-request reasons',
    category: 'ground-support-resources',
  },
  {
    id: 'wl-compliance',
    title: 'LVP Activation Compliance',
    visual: 'Required-versus-activated episodes and compliance percentage',
    category: 'weather-lvp',
  },
  {
    id: 'wl-timeliness',
    title: 'LVP Activation/Deactivation Timeliness',
    visual: 'Separate activation and deactivation lag distributions',
    category: 'weather-lvp',
  },
  {
    id: 'wl-rvr',
    title: 'RVR Availability',
    visual: 'Valid runway visual range samples versus expected samples',
    category: 'weather-lvp',
  },
  {
    id: 'wl-metar-availability',
    title: 'METAR Availability Rate',
    visual: 'Received expected reports %, missing-report timeline',
    category: 'weather-lvp',
  },
  {
    id: 'wl-metar-timeliness',
    title: 'METAR Issuance Timeliness',
    visual: 'Reports issued within configured deadline %, delay table',
    category: 'weather-lvp',
  },
  {
    id: 'wl-delay',
    title: 'Weather-Related Delay %',
    visual: 'Weather-attributed delayed flights versus eligible flights',
    category: 'weather-lvp',
  },
  {
    id: 'wl-disruption',
    title: 'Weather Disruption Duration',
    visual: 'Union of disruption intervals, episode timeline',
    category: 'weather-lvp',
  },
  {
    id: 'oe-capacity',
    title: 'Airside Capacity Utilization',
    visual: 'Demand/capacity by domain; no unapproved composite score',
    category: 'operational-efficiency',
  },
  {
    id: 'oe-stand-efficiency',
    title: 'Aircraft Stand Turnaround Efficiency',
    visual: 'Planned versus actual stand-turn duration and compliant turns',
    category: 'operational-efficiency',
  },
  {
    id: 'oe-taxi-efficiency',
    title: 'Taxi Efficiency',
    visual: 'Reference versus actual taxi duration, configured efficiency ratio',
    category: 'operational-efficiency',
  },
  {
    id: 'oe-reallocation',
    title: 'Gate/Stand Reallocation Rate',
    visual: 'Reallocated assignments %, original/final allocation table',
    category: 'operational-efficiency',
  },
  {
    id: 'oe-recovery',
    title: 'Operational Disruption Recovery Time',
    visual: 'Disruption-to-confirmed-recovery duration by episode',
    category: 'operational-efficiency',
  },
  {
    id: 'ra-resource-report',
    title: 'Granularity Reports – Resource Utilization',
    visual: 'Report with 15-minute/hour/day aggregation and CSV',
    category: 'reporting-analytics',
  },
  {
    id: 'ra-feed-failure',
    title: 'Data-Feed Failure Rate',
    visual: 'Failed expected deliveries %, source status history',
    category: 'reporting-analytics',
  },
  {
    id: 'ra-drills',
    title: 'Emergency Drill Completion Rate',
    visual: 'Completed scheduled drills %, due/completed drill table',
    category: 'reporting-analytics',
  },
  {
    id: 'to-bags',
    title: 'First Bag & Last Bag Delivery Time',
    visual: 'Paired arrival-to-first-bag and arrival-to-last-bag metrics',
    category: 'terminal-operations',
  },
  {
    id: 'to-cute',
    title: 'CUTE (Airline Check-in Counter) Utilization',
    visual: 'Active eligible counter-minutes versus available counter-minutes',
    category: 'terminal-operations',
  },
  {
    id: 'to-reconciliation',
    title: 'Baggage Reconciliation Accuracy',
    visual: 'Correctly reconciled eligible bags %, discrepancy table',
    category: 'terminal-operations',
  },
  {
    id: 'to-runway-report-accuracy',
    title: 'Runway Utilization Report Accuracy',
    visual: 'Report/reference comparison under configured tolerance',
    category: 'terminal-operations',
  },
  {
    id: 'to-predictive-flow',
    title: 'Predictive Passenger Flow & Dynamic Resource Allocation',
    visual: 'Precomputed forecast versus actual plus explicitly simulated allocation scenario',
    category: 'terminal-operations',
  },
  {
    id: 'pf-throughput',
    title: 'Passenger Throughput vs. Terminal Capacity',
    visual: 'Passengers per interval versus matching interval capacity',
    category: 'passenger-flow',
  },
  {
    id: 'pf-boarding',
    title: 'Processing Time - Boarding Gate',
    visual: 'Service duration distribution by boarding gate',
    category: 'passenger-flow',
  },
  {
    id: 'pf-immigration-processing',
    title: 'Processing Time - Immigration',
    visual: 'Service duration distribution by immigration zone',
    category: 'passenger-flow',
  },
  {
    id: 'pf-checkin-wait',
    title: 'Check-in Queue Wait Time',
    visual: 'Wait minutes by terminal/counter group',
    category: 'passenger-flow',
  },
  {
    id: 'pf-security-wait',
    title: 'Security Queue Wait Time',
    visual: 'Wait minutes by checkpoint with labeled thresholds',
    category: 'passenger-flow',
  },
  {
    id: 'pf-immigration-wait',
    title: 'Immigration Queue Wait Time',
    visual: 'Wait minutes by immigration zone',
    category: 'passenger-flow',
  },
  {
    id: 'pf-satisfaction',
    title: 'Passenger Satisfaction Index',
    visual: 'Configured weighted score, response count and dimension breakdown',
    category: 'passenger-flow',
  },
] as const;
export type KpiId = (typeof entries)[number]['id'];
export type Definition = (typeof entries)[number];
export const catalog = Object.fromEntries(entries.map((e) => [e.id, e])) as Record<
  KpiId,
  Definition
>;
export function categoryEntries(id: CategoryId) {
  return entries.filter((e) => e.category === id);
}
export function isCategory(value: string): value is CategoryId {
  return categories.some((c) => c.id === value);
}
